# headers and icon 
title: Miles Chan
info: PhD Aerospace Engineering '24 @ Caltech
icon-pic: assets/img/ms-icon-310x310.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
